let suggestions = [
    "Chennai",
    "Nagpur",
    "Pune",
    "Kanpur",
    "Goa",
    "Kota",
    "Ahemdabad",
    "Bombay",
    "Banglore",
    "Assam",
    "Delhi",
    "Madras",
    "Dehradun",
    "Kolkata",
    "Manali",
    "Shimla",
    "Banaras",
    "Dwarka",
    "Oty",
    "How to learn JavaScript",
    "How to became Freelancer",
    "How to became Web Designer",
    "How to start Gaming Channel",
    "How to start YouTube Channel",
    "What does HTML stands for?",
    "What does CSS stands for?",
];